fix coffee-script/register error when running test
When I ran test with the old file I had this error : 

Running mocha caught exception: 
Error: Command failed: 
/home/baremec/.node/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:210
          throw new Error("Use CoffeeScript.register() or require the coffee-s
                ^
Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.
  at Object.base.(anonymous function) [as .coffee] (/home/baremec/.node/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:210:17)

I found a solution here : https://github.com/github/generator-hubot/pull/6